import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || null);

    useEffect(() => {
        if (language) {
            localStorage.setItem('language', language);
        } else {
            localStorage.removeItem('language');
        }
    }, [language]);

    const translations = {
        'English': {
            'welcome': 'Welcome',
            'login': 'Login',
            'register': 'Register',
            'home': 'Home',
            'offer_service': 'Offer Service',
            'request_help': 'Request Help',
            'alerts': 'Alerts',
            'my_activity': 'My Activity',
            'community_reach': 'Community Reach',
            'active_users': 'Active Users',
            'local_professionals': 'Local Professionals',
            'pros_nearby': 'Pros Nearby',
            'admin_login': 'Admin Login',
            'explore_city': 'Explore Your City',
            'discover': 'Discover',
            'others': 'Others',
            'software': 'Software',
            'medical': 'Medical',
            'teaching': 'Teaching',
            'business': 'Business',
            'plumbing': 'Plumbing',
            'student': 'Student',
            'employed': 'Employed',
            'homemaker': 'Homemaker',
            'education_level_label': 'Education Level',
            'course_label': 'Course / Subject',
            'high_school': 'High School',
            'intermediate': 'Intermediate',
            'undergraduate': 'Undergraduate',
            'postgraduate': 'Postgraduate',
            'phd': 'PhD',
            'welcome_back_msg': 'Welcome back to your SmartHood',
            'name_label': 'Name or Unique ID',
            'name_placeholder': 'Tell us your name',
            'phone_label': 'Phone Number',
            'phone_placeholder': '10-digit mobile number',
            'sign_in': 'Sign In',
            'secure_login': 'Secure Passwordless Login',
            'join_smarthood': 'Join SmartHood',
            'community_connect': 'Connect with your local community today',
            'personal': 'Personal',
            'location': 'Location',
            'work': 'Work',
            'age': 'Age',
            'gender': 'Gender',
            'blood_group': 'Blood Group',
            'email': 'Email',
            'continue_location': 'Continue to Location',
            'next_step': 'Next Step',
            'back': 'Back',
            'occupation_type': 'Occupation Type',
            'complete_join': 'Complete & Join',
            'already_account': 'Already have an account?',
            'login_here': 'Login here',
            'locality_label': 'Locality / Community',
            'town_label': 'Town / Village',
            'district_label': 'District',
            'state_label': 'State',
            'address_label': 'Full Address',
            'experience_label': 'Years of Experience',
            'job_role_label': 'Job Role',
            'sector_label': 'Sector / Industry',
            'business_type_label': 'Business Type',
            'description_label': 'Description / Details',
            'welcome_back_user': 'Welcome Back',
            'professionals_locality': 'Professionals in your locality',
            'invite_neighbors': 'Invite neighbors!',
            'creating': 'Creating...',
            'processing': 'Processing...',
            'profile': 'Profile',
            'logout': 'Logout',
            'admin_panel': 'Admin Panel',
            'completed': 'Completed',
            'job_done': 'Job Done!',
            'completed_by': 'Completed by',
            'total_spend': 'Total Spend',
            'interested_providers': 'Interested Providers',
            'no_interest': 'No providers have expressed interest yet.',
            'work_finished_q': 'Has the work been done?',
            'work_finished_msg': 'Once the work is finished, you must mark it as complete.',
            'mark_completed': 'Mark as Completed',
            'interest_sent': 'Interest Sent',
            'im_interested': "I'm Interested",
            'work_completion_form': 'Work Completion Form',
            'confirm_provider_msg': 'Please confirm the provider who completed the job.',
            'provider_unique_id': 'Provider Unique ID',
            'amount_paid': 'Amount Paid',
            'confirm_completion': 'Confirm Completion',
            'failed_load_service': 'Failed to load service',
            'action_failed': 'Action failed',
            'id_mandatory': 'Provider Unique ID is mandatory',
            'service_completed_success': 'Service Completed Successfully!',
            'completion_failed': 'Completion failed',
            'offer_service_title': 'Offer a Service',
            'broadcast_locality': 'Broadcast to your locality',
            'service_title': 'Service Title',
            'describe_service_placeholder': 'Describe your service in detail...',
            'attach_media': 'Attach Media',
            'who_receive_q': 'Who should receive this?',
            'everyone': 'Everyone',
            'specific_pro': 'Specific Professional',
            'select_profession': 'Select Profession',
            'choose_role': '-- Choose Role --',
            'publish_offer': 'PUBLISH OFFER',
            'confirm_post': 'Confirm Post',
            'confirm_and_post': 'Confirm & Post',
            'community_support': 'Community Support',
            'privacy_protected': 'Privacy Protected',
            'privacy_msg': 'Your contact details are hidden until you accept an offer.',
            'broadcast_request': 'BROADCAST REQUEST',
            'posting': 'Posting...',
            'confirm_request': 'Confirm Request',
            'fill_all_fields': 'Please fill in title and description',
            'offer_service_success': 'Service Offer Posted Successfully!',
            'request_service_success': 'Request Sent Successfully!',
            'failed_send_request': 'Failed to send request',
            'failed_post_offer': 'Failed to post offer',
            'target_community': 'Target Community',
            'current_locality_default': 'Current Locality (Default)',
            'target_loc_offer_helper': '* Default: Your offer appears in your home locality. Change this to target another area.',
            'target_loc_req_helper': '* Default: Your request appears in your home locality. Change this to target another area.',
            'overview': 'Overview',
            'discover_title': 'Discover Your Town',
            'city_spots_msg': 'Find the best spots, events and communities nearby',
            'search_placeholder': 'Search for events or places...',
            'popular_now': 'Popular Now',
            'no_events': 'No events found in your area',
            'check_later': 'Check back later for community updates',
            'food': 'Food',
            'sports': 'Sports',
            'culture': 'Culture',
            'emergency_center': 'Emergency Center',
            'emergency_desc': 'Immediate help from your locality',
            'broadcast_alert': 'Broadcast Alert',
            'select_emergency_type': 'Select Emergency Type',
            'blood_donation': 'Blood Donation',
            'accident': 'Accident',
            'theft': 'Theft',
            'climate_alert': 'Climate Alert',
            'cash_donation': 'Cash Donation',
            'blood_group_req': 'Select Required Blood Group',
            'alert_desc_placeholder': 'Describe the emergency here...',
            'alert_sent_success': 'Alert broadcasted successfully to your locality',
            'sending_alert': 'Broadcasting alert',
            'financial': 'Financial',
            'active_list': 'Active List',
            'engagement': 'Engagement',
            'loading_activity': 'Loading your activity...',
            'my_activity_dashboard': 'My Activity Dashboard',
            'track_impact': 'Track your community impact and performance',
            'impact_score': 'Impact Score',
            'locality_rank': 'Locality Rank',
            'financial_summary': 'Financial Summary',
            'earned': 'Earned',
            'spent': 'Spent',
            'services_summary': 'Services Summary',
            'offered': 'Offered',
            'requested': 'Requested',
            'total_revenue_earned': 'Total Revenue Earned',
            'total_money_spent': 'Total Money Spent',
            'monthly_breakdown': 'Monthly Breakdown',
            'no_monthly_data': 'No monthly data available',
            'my_active_posts': 'My Active Posts',
            'no_active_services': 'No active services.',
            'post_to_start': 'Post an offer or request to get started!',
            'badges_earned': 'Badges Earned',
            'complete_for_badges': 'Complete more activities to earn badges!',
            'recent_activity': 'Recent Activity',
            'no_recent_activity': 'No recent activity',
            'alert_participation': 'Alert Participation',
            'alerts_responded': 'Alerts you\'ve responded to',

            'notifications': 'Notifications',
            'unread_notifications': 'unread notifications',
            'mark_all_read': 'Mark all read',
            'all': 'All',
            'unread': 'Unread',
            'no_notifications': 'No notifications yet',
            'loading_notifications': 'Loading notifications...',

            'emergency': 'Emergency',
            'official': 'Official',
            'welfare': 'Welfare',
            'entertainment': 'Entertainment',
            'emergency_type': 'Emergency Type',
            'select_blood_group': 'Select Required Group',
            'alert_details': 'Alert Details',
            'alert_success': 'Alert Broadcasted Successfully',
            'alert_failed': 'Failed to send alert',
            'emergency_placeholder': 'describe location and urgency...',
            'broadcast': 'Broadcast',
            'start_here': '-- Start Here --',
            'listening': 'Listening...',
            'total_users': 'Total Users',
            'service_offers': 'Service Offers',
            'service_requests': 'Service Requests',
            'total_revenue': 'Total Revenue',
            'admin_analytics': 'Admin Analytics',
            'user_growth_locality': 'User Growth by Locality',
            'community_events': 'Community Events',
            'events_locality': 'events in your locality',
            'upcoming': 'Upcoming',
            'past': 'Past',
            'create': 'Create',

            'event_title': 'Event Title',
            'venue': 'Venue',
            'date': 'Date',
            'time': 'Time',
            'category': 'Category',
            'community': 'Community',

            'create_event': 'Create Event',
            'loading_neighborhood': 'Loading your neighborhood...',
            'live': 'Live',
            'no_active_states': 'No active states found yet.',
            'no_professionals_locality': 'No professionals found in your locality yet. Invite neighbors!',
            'no_professionals_modal': 'No professionals found',
            'yrs_exp': 'years exp',
            'professional': 'Professional',
            'loading': 'Loading...',
            'visibility': 'Visibility',
            'my_community_default': 'My Community (Default)',
            'broadcast_home_note': '* Your request is always broadcast to your home community.',
            'other_communities_in': 'Other Communities in',
            'select_all': 'Select All',
            'deselect_all': 'Deselect All',
            'finding_communities': 'Finding nearby communities...',
            'select_communities_hint': 'Select communities to broadcast your request across multiple areas',
            'select_professions': 'Select Professions *',
            'selected_count': 'selected',
            'no_professions_locality': 'No professions available in your locality',
            'professions_hint': '* Showing professions registered in your locality. Select one or more.',
            'send_to_other_communities': 'Send to Other Communities',
            'broadcast_additional_hint': 'Broadcast your request to additional communities in your town',
            'broadcast_offer_hint': 'Broadcast your offer to additional communities in your town',
            'no_other_communities': 'No other communities available in your town',
            'communities_selected': 'communities selected',
            'users_count_suffix': 'users',
            'post_confirmation_msg': 'This will be posted to all users in your locality.',
            'select_profession_alert': 'Please select at least one profession when targeting specific professionals',
            'new_user_prompt': "Don't have an account? Register",
            'views': 'Views',
            'viewed_by': 'Viewed By',
            'no_views_yet': 'No views yet'
        },
        'Telugu': {
            'welcome': 'స్వాగతం',
            'login': 'లాగిన్',
            'register': 'నమోదు',
            'home': 'హోమ్',
            'offer_service': 'సర్వీస్ ఇవ్వండి',
            'request_help': 'సహాయం కోరండి',
            'alerts': 'హెచ్చరికలు',
            'my_activity': 'నా కార్యకలాపాలు',
            'community_reach': 'కమ్యూనిటీ విస్తృతి',
            'active_users': 'క్రియాశీల వినియోగదారులు',
            'local_professionals': 'స్థానిక నిపుణులు',
            'pros_nearby': 'నిపుణులు అందుబాటులో ఉన్నారు',
            'admin_login': 'అడ్మిన్ లాగిన్',
            'explore_city': 'మీ నగరాన్ని శోధించండి',
            'discover': 'కనుగొనండి',
            'others': 'ఇతరులు',
            'software': 'సాఫ్ట్‌వేర్',
            'medical': 'వైద్య',
            'teaching': 'బోధన',
            'business': 'వ్యాపారం',
            'plumbing': 'ప్లంబింగ్',
            'student': 'విద్యార్థి',
            'employed': 'ఉద్యోగి',
            'homemaker': 'గృహిణి',
            'education_level_label': 'విద్యార్హత',
            'course_label': 'కోర్సు / సబ్జెక్టు',
            'high_school': 'హై స్కూల్',
            'intermediate': 'ఇంటర్మీడియట్',
            'undergraduate': 'డిగ్రీ (UG)',
            'postgraduate': 'పీజీ (PG)',
            'phd': 'పీహెచ్‌డీ',
            'welcome_back_msg': 'మీ స్మార్ట్‌హుడ్‌కు తిరిగి స్వాగతం',
            'name_label': 'పేరు లేదా ప్రత్యేక ఐడి',
            'name_placeholder': 'మీ పేరు తెలియజేయండి',
            'phone_label': 'ఫోన్ నంబర్',
            'phone_placeholder': '10 అంకెల మొబైల్ నంబర్',
            'sign_in': 'సైన్ ఇన్',
            'secure_login': 'సురక్షిత పాస్‌వర్డ్‌లెస్ లాగిన్',
            'join_smarthood': 'స్మార్ట్‌హుడ్‌లో చేరండి',
            'community_connect': 'ఈరోజే మీ స్థానిక కమ్యూనిటీతో కనెక్ట్ అవ్వండి',
            'personal': 'వ్యక్తిగత',
            'location': 'స్థలం',
            'work': 'పని',
            'age': 'వయస్సు',
            'gender': 'లింగము',
            'blood_group': 'రక్త వర్గం',
            'email': 'ఈమెయిల్',
            'continue_location': 'స్థానానికి కొనసాగండి',
            'next_step': 'తదుపరి దశ',
            'back': 'వెనుకకు',
            'occupation_type': 'వృత్తి రకం',
            'complete_join': 'పూర్తి చేసి చేరండి',
            'already_account': 'ఇప్పటికే ఖాతా ఉందా?',
            'login_here': 'ఇక్కడ లాగిన్ అవ్వండి',
            'locality_label': 'ప్రాంతం / కమ్యూనిటీ',
            'town_label': 'పట్టణం / గ్రామం',
            'district_label': 'జిల్లా',
            'state_label': 'రాష్ట్రం',
            'address_label': 'పూర్తి చిరునామా',
            'experience_label': 'అనుభవం (సంవత్సరాలు)',
            'job_role_label': 'ఉద్యోగ హోదా',
            'sector_label': 'రంగం / పరిశ్రమ',
            'business_type_label': 'వ్యాపార రకం',
            'description_label': 'వివరాలు',
            'welcome_back_user': 'తిరిగి స్వాగతం',
            'professionals_locality': 'మీ ప్రాంతంలోని నిపుణులు',
            'invite_neighbors': 'పొరుగువారిని ఆహ్వానించండి!',
            'creating': 'సృష్టిస్తోంది...',
            'processing': 'ప్రక్రియలో ఉంది...',
            'profile': 'ప్రొఫైల్',
            'logout': 'లాగౌట్',
            'admin_panel': 'అడ్మిన్ ప్యానెల్',
            'completed': 'పూర్తయింది',
            'job_done': 'పని పూర్తయింది!',
            'completed_by': 'పూర్తి చేసిన వారు',
            'total_spend': 'మొత్తం ఖర్చు',
            'interested_providers': 'ఆసక్తి గల నిపుణులు',
            'no_interest': 'ఇప్పటి వరకు ఎవరూ ఆసక్తి చూపలేదు.',
            'work_finished_q': 'పని పూర్తయిందా?',
            'work_finished_msg': 'పని పూర్తయిన తర్వాత, మీరు దానిని పూర్తయినట్లుగా గుర్తించాలి.',
            'mark_completed': 'పూర్తయినట్లుగా గుర్తించు',
            'interest_sent': 'ఆసక్తి వ్యక్తం చేయబడింది',
            'im_interested': 'నేను చేయగలను',
            'work_completion_form': 'పని పూర్తి ఫారం',
            'confirm_provider_msg': 'పనిని పూర్తి చేసిన నిపుణుడిని దయచేసి నిర్ధారించండి.',
            'provider_unique_id': 'నిపుణుడి యూనిక్ ఐడి',
            'amount_paid': 'చెల్లించిన మొత్తం',
            'confirm_completion': 'పూర్తి చేయుటను నిర్ధారించు',
            'failed_load_service': 'సర్వీస్ లోడ్ చేయడం విఫలమైంది',
            'action_failed': 'పని విఫలమైంది',
            'id_mandatory': 'నిపుణుడి యూనిక్ ఐడి తప్పనిసరి',
            'service_completed_success': 'సర్వీస్ విజయవంతంగా పూర్తయింది!',
            'completion_failed': 'పూర్తి చేయడం విఫలమైంది',
            'offer_service_title': 'సర్వీస్ ఇవ్వండి',
            'broadcast_locality': 'మీ ప్రాంతంలో అందరికీ తెలియజేయండి',
            'service_title': 'సర్వీస్ పేరు',
            'describe_service_placeholder': 'మీ సర్వీస్ గురించి వివరంగా చెప్పండి...',
            'attach_media': 'మీడియా జత చేయండి',
            'who_receive_q': 'ఇది ఎవరికి అందాలి?',
            'everyone': 'అందరికీ',
            'specific_pro': 'నిర్దిష్ట నిపుణులు',
            'select_profession': 'వృత్తిని ఎంచుకోండి',
            'choose_role': '-- పాత్రను ఎంచుకోండి --',
            'publish_offer': 'ఆఫర్‌ను ప్రచురించు',
            'confirm_post': 'పోస్ట్‌ను నిర్ధారించండి',
            'confirm_and_post': 'నిర్ధారించి పోస్ట్ చేయి',
            'community_support': 'కమ్యూనిటీ మద్దతు',
            'privacy_protected': 'గోప్యత రక్షించబడింది',
            'privacy_msg': 'మీరు ఆఫర్‌ను అంగీకరించే వరకు మీ వివరాలు ఎవరికీ తెలియవు.',
            'broadcast_request': 'సహాయం కోరండి',
            'posting': 'పంపుతున్నాము...',
            'confirm_request': 'నిర్ధారించండి',
            'fill_all_fields': 'దయచేసి పేరు మరియు వివరాలను తెలియజేయండి',
            'offer_service_success': 'సర్వీస్ ఆఫర్ విజయవంతంగా పోస్ట్ చేయబడింది!',
            'request_service_success': 'అభ్యర్థన విజయవంతంగా పంపబడింది!',
            'failed_send_request': 'అభ్యర్థన పంపడం విఫలమైంది',
            'failed_post_offer': 'ఆఫర్ పోస్ట్ చేయడం విఫలమైంది',
            'target_community': 'లక్ష్య ప్రాంతం',
            'current_locality_default': 'ప్రస్తుత ప్రాంతం (డిఫాల్ట్)',
            'target_loc_offer_helper': '* డిఫాల్ట్: మీ ఆఫర్ మీ సొంత ప్రాంతంలో కనిపిస్తుంది. వేరే ప్రాంతాన్ని లక్ష్యంగా చేసుకోవడానికి దీనిని మార్చండి.',
            'target_loc_req_helper': '* డిఫాల్ట్: మీ అభ్యర్థన మీ సొంత ప్రాంతంలో కనిపిస్తుంది. వేరే ప్రాంతాన్ని లక్ష్యంగా చేసుకోవడానికి దీనిని మార్చండి.',
            'overview': 'అవలోకనం',
            'discover_title': 'మీ పట్టణాన్ని కనుగొనండి',
            'city_spots_msg': 'సమీపంలోని ఉత్తమ ప్రదేశాలు, ఈవెంట్‌లు మరియు కమ్యూనిటీలను కనుగొనండి',
            'search_placeholder': 'ఈవెంట్‌లు లేదా ప్రదేశాల కోసం వెతకండి...',
            'popular_now': 'ప్రస్తుతం జనాదరణ పొందినవి',
            'no_events': 'మీ ప్రాంతంలో ఈవెంట్‌లు ఏవీ కనుగొనబడలేదు',
            'check_later': 'కమ్యూనిటీ అప్‌డేట్‌ల కోసం మళ్లీ చూడండి',
            'food': 'ఆహారం',
            'sports': 'క్రీడలు',
            'culture': 'సంస్కృతి',
            'emergency_center': 'అత్యవసర కేంద్రం',
            'emergency_desc': 'మీ ప్రాంతం నుండి తక్షణ సహాయం',
            'broadcast_alert': 'అలర్ట్ పంపండి',
            'select_emergency_type': 'అత్యవసర రకాన్ని ఎంచుకోండి',
            'blood_donation': 'రక్తదానం',
            'accident': 'ప్రమాదం',
            'theft': 'దొంగతనం',
            'climate_alert': 'వాతావరణ అలర్ట్',
            'cash_donation': 'నగదు విరాళం',
            'blood_group_req': 'అవసరమైన రక్త సమూహాన్ని ఎంచుకోండి',
            'alert_desc_placeholder': 'అత్యవసర పరిస్థితిని ఇక్కడ వివరించండి...',
            'alert_sent_success': 'అలర్ట్ మీ ప్రాంతానికి విజయవంతంగా పంపబడింది',
            'sending_alert': 'అలర్ట్ పంపిస్తున్నాము',
            'financial': 'ఆర్థిక',
            'active_list': 'క్రియాశీల జాబితా',
            'engagement': 'భాగస్వామ్యం',
            'loading_activity': 'మీ కార్యకలాపాలను లోడ్ చేస్తున్నాము...',
            'my_activity_dashboard': 'నా కార్యకలాపాల డాష్‌బోర్డ్',
            'track_impact': 'మీ కమ్యూనిటీ ప్రభావం మరియు పనితీరును ట్రాక్ చేయండి',
            'impact_score': 'ప్రభావ స్కోరు',
            'locality_rank': 'ప్రాంతీయ ర్యాంక్',
            'financial_summary': 'ఆర్థిక సారాంశం',
            'earned': 'సంపాదించినవి',
            'spent': 'ఖర్చు చేసినవి',
            'services_summary': 'సర్వీసుల సారాంశం',
            'offered': 'ఇచ్చినవి',
            'requested': 'కోరినవి',
            'total_revenue_earned': 'మొత్తం సంపాదన',
            'total_money_spent': 'మొత్తం ఖర్చు',
            'monthly_breakdown': 'నెలవారీ వివరాలు',
            'no_monthly_data': 'నెలవారీ డేటా అందుబాటులో లేదు',
            'my_active_posts': 'నా క్రియాశీల పోస్ట్‌లు',
            'no_active_services': 'క్రియాశీల సర్వీసులు లేవు.',
            'post_to_start': 'ప్రారంభించడానికి ఒక ఆఫర్ లేదా అభ్యర్థనను పోస్ట్ చేయండి!',
            'badges_earned': 'పొందిన బ్యాడ్జ్‌లు',
            'complete_for_badges': 'బ్యాడ్జ్‌లను సంపాదించడానికి మరిన్ని పనులు పూర్తి చేయండి!',
            'recent_activity': 'ఇటీవలి కార్యకలాపాలు',
            'no_recent_activity': 'ఇటీవలి కార్యకలాపాలు లేవు',
            'alert_participation': 'అలర్ట్ భాగస్వామ్యం',
            'alerts_responded': 'మీరు స్పందించిన అలర్ట్‌లు',
            'spots': 'ప్రసిద్ధ స్థలాలు',
            'notifications': 'ప్రకటలు (నోటిఫికేషన్లు)',
            'unread_notifications': 'చదవని ప్రకటలు',
            'mark_all_read': 'అన్నీ చదివినట్లుగా గుర్తించు',
            'all': 'అన్నీ',
            'unread': 'చదవనివి',
            'no_notifications': 'ప్రకటలు ఏమీ లేవు',
            'loading_notifications': 'ప్రకటలను లోడ్ చేస్తున్నాము...',
            'emergency': 'అత్యవసర',
            'official': 'అధికారిక',
            'welfare': 'సంక్షేమ',
            'entertainment': 'వినోదం',
            'emergency_type': 'అత్యవసర రకం',
            'select_blood_group': 'అవసరమైన రక్త వర్గాన్ని ఎంచుకోండి',
            'alert_details': 'హెచ్చరిక వివరాలు',
            'alert_success': 'హెచ్చరిక విజయవంతంగా ప్రసారం చేయబడింది',
            'alert_failed': 'హెచ్చరిక పంపడం విఫలమైంది',
            'emergency_placeholder': 'స్థలం మరియు అత్యవసరత గురించి వివరించండి...',
            'broadcast': 'ప్రసారం చేయండి',
            'start_here': '-- ఇక్కడ ప్రారంభించండి --',
            'listening': 'వింటున్నారు...',
            'total_users': 'మొత్తం వినియోగదారులు',
            'service_offers': 'సర్వీస్ ఆఫర్లు',
            'service_requests': 'సర్వీస్ అభ్యర్థనలు',
            'total_revenue': 'మొత్తం ఆదాయం',
            'admin_analytics': 'అడ్మిన్ విశ్లేషణలు',
            'user_growth_locality': 'ప్రాంతాల వారీగా వినియోగదారుల వృద్ధి',
            'community_events': 'కమ్యూనిటీ ఈవెంట్‌లు',
            'events_locality': 'మీ ప్రాంతంలోని ఈవెంట్‌లు',
            'upcoming': 'రాబోయేవి',
            'past': 'ముగిసినవి',
            'create': 'సృష్టించు',
            'educational': 'విద్యా సంబంధిత',
            'cultural': 'సాంస్కృతిక',
            'religious': 'మతపరమైన',
            'event_title': 'ఈవెంట్ పేరు',
            'venue': 'వేదిక',
            'broadcast_additional_hint': 'మీ అభ్యర్థనను మీ పట్టణంలోని అదనపు కమ్యూనిటీలకు ప్రసారం చేయండి',
            'broadcast_offer_hint': 'మీ ఆఫర్‌ను మీ పట్టణంలోని అదనపు కమ్యూనిటీలకు ప్రసారం చేయండి',
            'no_other_communities': 'మీ పట్టణంలో ఇతర కమ్యూనిటీలు అందుబాటులో లేవు',
            'communities_selected': 'కమ్యూనిటీలు ఎంచుకోబడ్డాయి',
            'users_count_suffix': 'వినియోగదారులు',
            'post_confirmation_msg': 'ఇది మీ ప్రాంతంలోని వినియోగదారులందరికీ పోస్ట్ చేయబడుతుంది.',
            'select_profession_alert': 'నిర్దిష్ట నిపుణులను లక్ష్యంగా చేసుకున్నప్పుడు దయచేసి కనీసం ఒక వృత్తిని ఎంచుకోండి',
            'date': 'తేదీ',
            'time': 'సమయం',
            'category': 'వర్గం',
            'community': 'కమ్యూనిటీ',
            'create_event': 'ఈవెంట్‌ను సృష్టించు',
            'new_user_prompt': 'ఖాతా లేదా? ఇక్కడ నమోదు చేసుకోండి',
            'loading_neighborhood': 'మీ ప్రాంత వివరాలు లోడ్ అవుతున్నాయి...',
            'live': 'లైవ్',
            'no_active_states': 'క్రియాశీల రాష్ట్రాలు కనుగొనబడలేదు.',
            'no_professionals_locality': 'మీ ప్రాంతంలో నిపుణులు ఎవరూ లేరు. పొరుగువారిని ఆహ్వానించండి!',
            'no_professionals_modal': 'నిపుణులు కనుగొనబడలేదు',
            'yrs_exp': 'సంవత్సరాల అనుభవం',
            'professional': 'వృత్తి నిపుణుడు',
            'loading': 'లోడ్ అవుతోంది...',
            'views': 'వీక్షణలు',
            'viewed_by': 'వీక్షించిన వారు',
            'no_views_yet': 'ఇంకా ఎవరూ చూడలేదు'
        }
    };

    const t = (key) => {
        if (!language) return key;
        return translations[language]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
